"""The patient health assistant (spec §18-21).

Three endpoints, and the boundaries between them are the safety design:

* ``POST /assistant/chat`` answers a question. Grounded in the patient's own
  prescriptions and appointments, validated on the way out, and escalated by a
  deterministic layer the model cannot argue with.
* ``POST /assistant/symptoms`` extracts symptoms from what the patient said —
  typed or transcribed from speech — and hands them back **for correction**. It
  writes nothing.
* ``POST /assistant/symptoms/confirm`` stores the corrected list as
  ``ReportedSymptom`` rows with source ``PATIENT_REPORTED`` or ``AI_ASSISTED``.
* ``POST /assistant/chat/image`` is ``/chat`` with a photographed report or
  prescription attached. The image is read by the model for that one answer
  and **never stored**: it is not a document upload, and a patient who wants
  the report kept uses the documents page, where retention and access are
  governed. Same consent, same validation, same escalation.

That last distinction is spec §21 and conflict C7: a symptom the patient
described is *patient-reported information*, not a physician's finding. It sits
in a staging table with its provenance recorded, and only a doctor's explicit
promotion turns it into a medical record. There is no code path from this module
into ``medical_records``.

Consent gates everything here: the assistant sends the patient's words to an
external provider, which is exactly what AI consent covers (conflict C2).
"""

from __future__ import annotations

import time
import uuid
from datetime import UTC, date, datetime, timedelta
from typing import Annotated, Any

from fastapi import APIRouter, Depends, File, Form, Query, Request, UploadFile
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import select

from app.api.deps import CurrentAuth, DbSession, client_ip, require_permission
from app.api.responses import ok
from app.core.config import settings
from app.core.errors import AppError, ErrorCode, bad_request, forbidden
from app.core.ratelimit import limit
from app.db.base import new_id, utcnow
from app.db.enums import (
    AppointmentStatus,
    AuditAction,
    DataSource,
    InputType,
    Role,
    UserStatus,
)
from app.db.models import (
    AIInteraction,
    Appointment,
    Doctor,
    Patient,
    Prescription,
    ReportedSymptom,
    User,
)
from app.modules.appointments import service as appointments_service
from app.modules.appointments.schedule import clinic_timezone, parse_windows, to_clinic
from app.modules.audit.service import AuditEntry, record_audit
from app.modules.auth.rbac import Permission
from app.services import ai, assistant, triage
from app.services.files import FileRejectedError, inspect_upload

router = APIRouter(prefix="/assistant", tags=["assistant"])

RequireAiChat = Annotated[object, Depends(require_permission(Permission.AI_CHAT))]

#: A question longer than this is not a question. The cap also bounds what a
#: single request can send to the provider.
MAX_QUESTION_LENGTH = 2000

#: An attached report is sent inline to the provider, so it is capped well
#: below the documents limit: a phone photo of a page is a few megabytes, and
#: anything larger is a scan that belongs on the documents page.
MAX_ATTACHMENT_BYTES = min(settings.MAX_UPLOAD_BYTES, 8 * 1024 * 1024)

#: The model reads images. A PDF is a document, and the documents page already
#: extracts those with a reviewable result.
ATTACHMENT_MIME_TYPES = frozenset({"image/jpeg", "image/png", "image/webp"})


class ChatRequest(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, populate_by_name=True)

    message: Annotated[str, Field(min_length=1, max_length=MAX_QUESTION_LENGTH)]
    #: Groups turns into one conversation. Generated by the client; it only ever
    #: scopes the patient's own history, so a guessed value reveals nothing.
    session_id: str | None = Field(default=None, alias="sessionId", max_length=64)
    input_type: InputType = Field(default=InputType.TEXT, alias="inputType")


class SymptomRequest(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, populate_by_name=True)

    text: Annotated[str, Field(min_length=1, max_length=MAX_QUESTION_LENGTH)]
    #: Accepted and validated, but not stored: this endpoint writes nothing.
    #: Provenance is recorded at the confirm step, where a row is actually
    #: created. Rejecting an unknown value here still matters — a client sending
    #: a bad one should learn about it before the patient has corrected a list.
    input_type: InputType = Field(default=InputType.TEXT, alias="inputType")


class ConfirmedSymptom(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    symptom: Annotated[str, Field(min_length=1, max_length=200)]
    severity: Annotated[str, Field(max_length=50)] | None = None
    duration: Annotated[str, Field(max_length=100)] | None = None


class ConfirmSymptomsRequest(BaseModel):
    """The patient's corrected list (spec §20: "allow the patient to correct")."""

    model_config = ConfigDict(populate_by_name=True)

    symptoms: Annotated[list[ConfirmedSymptom], Field(min_length=1, max_length=25)]
    input_type: InputType = Field(default=InputType.TEXT, alias="inputType")
    raw_text: Annotated[str, Field(max_length=MAX_QUESTION_LENGTH)] | None = Field(
        default=None, alias="rawText"
    )


async def _require_consenting_patient(auth: CurrentAuth, db: DbSession) -> Patient:
    """The assistant is for patients, and only with AI consent.

    Withdrawing consent disables this feature rather than degrading it: unlike
    document reading, there is no local model to fall back to, and the honest
    answer is to say the feature is off.
    """
    if auth.role != Role.PATIENT or not auth.patient_id:
        raise forbidden("The health assistant is for patients.")

    patient = (
        await db.execute(select(Patient).where(Patient.id == auth.patient_id))
    ).scalar_one_or_none()
    if patient is None:
        raise forbidden("This account has no patient record.")

    if not patient.ai_consent_active:
        raise AppError(
            403,
            ErrorCode.CONSENT_REQUIRED,
            "The health assistant needs your consent to process what you write. "
            "You can turn it on in your profile, and turn it off again at any time.",
        )
    return patient


async def _gather_context(db: DbSession, patient_id: str) -> tuple[str, list[str]]:
    """The patient's own data, and the medications the answer may mention.

    Returned together because they are the same fact used twice: as grounding
    for the model, and afterwards as the list any named drug is checked against.
    """
    medications = (
        (
            await db.execute(
                select(Prescription.medication, Prescription.dosage, Prescription.frequency)
                .where(Prescription.patient_id == patient_id, Prescription.active.is_(True))
                .limit(25)
            )
        )
        .all()
    )
    medication_names = [row.medication for row in medications]
    medication_lines = [
        f"{row.medication} {row.dosage} {row.frequency}" for row in medications
    ]

    appointments = (
        await db.execute(
            select(Appointment.start_time, User.name, Doctor.specialization)
            .join(Doctor, Doctor.id == Appointment.doctor_id)
            .join(User, User.id == Doctor.user_id)
            .where(
                Appointment.patient_id == patient_id,
                Appointment.start_time >= utcnow(),
                Appointment.status.in_(
                    [AppointmentStatus.REQUESTED, AppointmentStatus.CONFIRMED]
                ),
            )
            .order_by(Appointment.start_time)
            .limit(5)
        )
    ).all()
    appointment_lines = [
        f"{to_clinic(row.start_time).strftime('%d %b %Y at %H:%M')} with {row.name}"
        f" ({row.specialization})"
        for row in appointments
    ]

    # The specialities patients can actually be sent to — read from the doctors
    # who are here, not from a list of hospital departments. This platform
    # connects a patient to any doctor in the country rather than to a wing of
    # one building, so a department has nothing to route to: what decides where
    # somebody goes is what the available doctors *practise*.
    specialities = (
        (
            await db.execute(
                select(Doctor.specialization)
                .where(Doctor.specialization.is_not(None), Doctor.accepting_patients.is_(True))
                .distinct()
                .limit(40)
            )
        )
        .scalars()
        .all()
    )

    # Who it is talking to. Name, age and the two clinical facts that change
    # what advice is safe — an allergy the assistant does not know about is the
    # one it will cheerfully talk around.
    patient = (
        await db.execute(
            select(
                User.name,
                Patient.date_of_birth,
                Patient.blood_group,
                Patient.allergies,
                Patient.chronic_conditions,
            )
            .join(User, User.id == Patient.user_id)
            .where(Patient.id == patient_id)
        )
    ).first()

    patient_name: str | None = None
    facts: list[str] = []
    if patient is not None:
        patient_name = patient.name
        if patient.date_of_birth:
            years = int((utcnow() - patient.date_of_birth).days / 365.25)
            facts.append(f"Patient's age: {years}")
        if patient.blood_group:
            facts.append(f"Patient's blood group: {patient.blood_group}")
        # Stated as "none recorded" rather than omitted: silence about an
        # allergy reads to a model as "no allergies", and it is not the same
        # thing as nobody having asked.
        facts.append(
            f"Patient's allergies: {patient.allergies or 'none recorded'}"
        )
        facts.append(
            f"Patient's ongoing conditions: {patient.chronic_conditions or 'none recorded'}"
        )

    # The real directory, so "who can I see for my knee in Karachi" is answered
    # with a name that exists rather than a plausible invention. Only doctors a
    # patient could actually book: active, and taking patients.
    doctor_rows = (
        await db.execute(
            select(
                User.name,
                Doctor.specialization,
                Doctor.clinic_name,
                Doctor.city,
                Doctor.consultation_fee,
                Doctor.availability,
            )
            .join(User, User.id == Doctor.user_id)
            .where(
                User.status == UserStatus.ACTIVE,
                Doctor.accepting_patients.is_(True),
            )
            .order_by(User.name)
            .limit(60)
        )
    ).all()
    # Which weekdays each doctor actually sits.
    #
    # Without this the model has a name, a speciality and a fee, and no idea
    # whether the day somebody just asked for is one this doctor works — so it
    # proposes it, the diary has nothing, and the patient is told a time was
    # found that never existed. The windows are already on the row; naming the
    # days costs nothing and is the fact the question turns on.
    doctor_lines = [
        f"{row.name} — {row.specialization}"
        f" — {row.clinic_name or 'clinic not stated'}"
        f"{f', {row.city}' if row.city else ''}"
        f" — {settings.INVOICE_CURRENCY} {row.consultation_fee:.0f}"
        f" — sees patients on: {_working_days(row.availability)}"
        for row in doctor_rows
    ]

    context = assistant.build_context(
        patient_name=patient_name,
        patient_facts=facts,
        active_medications=medication_lines,
        upcoming_appointments=appointment_lines,
        specialities=list(specialities),
        doctors=doctor_lines,
        today=_clinic_today().strftime("%A, %d %B %Y"),
    )
    return context, medication_names


async def _recent_turns(
    db: DbSession, patient_id: str, session_id: str
) -> list[tuple[str, str]]:
    """Earlier exchanges of this conversation, oldest first.

    Filtered on the caller's own patient id as well as the session id, so a
    guessed session id can only ever pull the caller's own turns.
    """
    rows = (
        (
            await db.execute(
                select(AIInteraction.input, AIInteraction.response)
                .where(
                    AIInteraction.patient_id == patient_id,
                    AIInteraction.session_id == session_id,
                )
                .order_by(AIInteraction.created_at.desc())
                .limit(assistant.HISTORY_TURNS)
            )
        )
        .all()
    )
    return [(row.input, row.response) for row in reversed(rows)]


#: Monday is 1 in the stored windows, which is ISO's numbering.
_WEEKDAY_NAMES = {
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
    6: "Saturday",
    7: "Sunday",
}


def _clinic_today() -> date:
    """The date it is *at the clinic*, which is the one every answer is about.

    Not the server's. For five hours of every day those differ, and a patient
    told at 02:00 that tomorrow is Thursday when it is Thursday already has
    been told something false about their own day.
    """
    return datetime.now(UTC).astimezone(clinic_timezone()).date()


def _working_days(availability: object) -> str:
    """The weekdays a doctor publishes hours for, in words.

    Words rather than numbers because this goes to a language model and then,
    through it, to a patient: "Saturday and Sunday" is a sentence somebody can
    act on, and `[6, 7]` is a thing to be misread.
    """
    windows = parse_windows(availability)
    if not windows:
        return "no published hours yet"
    days = sorted({w.day_of_week for w in windows})
    return ", ".join(_WEEKDAY_NAMES.get(day, "?") for day in days)


async def _next_free_dates(db: DbSession, doctor_id: str, after: date, limit: int = 4) -> list[str]:
    """The next few dates this doctor actually has a free slot on.

    Read from the diary, not from the published hours: a day the doctor works
    but which is fully booked is not a day to offer somebody. Bounded to four
    weeks — past that the answer is "call them", not a longer list.
    """
    try:
        days = await appointments_service.availability(
            db, doctor_id, after, after + timedelta(days=28)
        )
    except AppError:
        return []
    free = [
        day["date"]
        for day in days
        if any(slot.get("available") for slot in day.get("slots", []))
    ]
    return free[:limit]


async def _resolve_booking(
    db: DbSession, doctor_name: str, on: str
) -> tuple[dict[str, Any] | None, dict[str, Any] | None]:
    """Turn "Dr Rajesh Iyer on 2026-09-04" into an offer, or into a reason.

    Returns ``(offer, problem)`` — exactly one of them, or two ``None`` when the
    line was so malformed there is nothing to say about it.

    **It used to return only the offer, and nothing when there was none.** The
    model had already written "I have found a time, confirm it on screen", so a
    patient asking for a day the doctor does not work was told a time had been
    found, shown no time, and left to work out which of the two was true. The
    reason now travels back with the failure and the client states it.

    **This books nothing.** It offers the first free slot, and a person taps to
    confirm. The model can misread a name or a weekday, and a wrong appointment
    costs a clinic slot and somebody's day — so the model proposes and the
    patient decides, which is the same shape the symptom flow already uses.
    """
    try:
        wanted = date.fromisoformat(on)
    except ValueError:
        return None, None

    # A date that has gone is refused here as well as in the prompt. The prompt
    # is guidance to a model that may ignore it; this is the rule.
    today = _clinic_today()
    if wanted < today:
        return None, {
            "reason": "past",
            "date": wanted.isoformat(),
            "today": today.isoformat(),
        }

    # Matched case-insensitively and loosely, because a model writes "Dr Rajesh
    # Iyer" for a row that reads "Rajesh Iyer". Exact-only would fail on the
    # commonest correct answer.
    cleaned = doctor_name.strip().removeprefix("Dr ").removeprefix("Dr. ").strip()
    row = (
        await db.execute(
            select(
                Doctor.id,
                User.name,
                Doctor.specialization,
                Doctor.consultation_fee,
                Doctor.availability,
            )
            .join(User, User.id == Doctor.user_id)
            .where(
                User.status == UserStatus.ACTIVE,
                Doctor.accepting_patients.is_(True),
                User.name.ilike(f"%{cleaned}%"),
            )
            .limit(2)
        )
    ).all()
    if not row:
        return None, {"reason": "unknown_doctor", "doctorName": cleaned}
    # Two matches means the name was ambiguous, and guessing between two doctors
    # is exactly the mistake this whole path is arranged to avoid.
    if len(row) > 1:
        return None, {"reason": "ambiguous_doctor", "doctorName": cleaned}

    doctor_id, name, speciality, fee, availability = row[0]

    try:
        days = await appointments_service.availability(db, doctor_id, wanted, wanted)
    except AppError:
        return None, {
            "reason": "not_bookable",
            "doctorId": doctor_id,
            "doctorName": name,
            "date": wanted.isoformat(),
        }

    free = [
        slot
        for day in days
        for slot in day.get("slots", [])
        if slot.get("available")
    ]
    if not free:
        # The two ways a day can have nothing are worth telling apart: a day the
        # doctor never works is answered with "they sit on Saturdays", and a day
        # they work but is full is answered with "that day is taken". Saying the
        # wrong one sends somebody to try a Wednesday again.
        works_today = any(w.day_of_week == wanted.isoweekday() for w in parse_windows(availability))
        return None, {
            "reason": "day_full" if works_today else "not_working",
            "doctorId": doctor_id,
            "doctorName": name,
            "date": wanted.isoformat(),
            "worksOn": _working_days(availability),
            # Concrete dates, because "Saturdays" still leaves somebody counting
            # forwards on a calendar to find one that is not already taken.
            #
            # Counted from today, not from the day they asked for. Somebody who
            # asks for the 9th and could have come on the 5th should be shown
            # the 5th; starting after their guess hides the sooner answer for
            # no reason, and the list is a suggestion rather than a constraint.
            "nextFree": await _next_free_dates(db, doctor_id, today),
        }

    first = free[0]
    return {
        "doctorId": doctor_id,
        "doctorName": name,
        "specialization": speciality,
        "fee": str(fee),
        "currency": settings.INVOICE_CURRENCY,
        "date": wanted.isoformat(),
        "startTime": first["startTime"],
        "endTime": first["endTime"],
        # Every other free time that day, so somebody who wants 4pm rather than
        # the first one does not have to abandon the conversation for the
        # booking screen.
        "alternatives": [
            {"startTime": slot["startTime"], "endTime": slot["endTime"]}
            for slot in free[1:6]
        ],
    }, None


async def _answer(
    *,
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    message: str,
    session_id: str | None,
    input_type: InputType,
    image: tuple[bytes, str] | None = None,
    attachment_name: str | None = None,
) -> dict[str, Any]:
    """The whole chat pipeline, shared by the JSON and the multipart route.

    Note the order: triage runs before the provider is contacted, so an
    emergency is escalated even when the provider is down, slow, or wrong.
    """
    patient = await _require_consenting_patient(auth, db)
    session_id = session_id or uuid.uuid4().hex

    assessment = triage.assess(message)
    context, medication_names = await _gather_context(db, patient.id)
    history = await _recent_turns(db, patient.id, session_id)

    started = time.perf_counter()
    try:
        answer = await assistant.ask(
            message,
            context=context,
            triage=assessment,
            allowed_medications=medication_names,
            history=history,
            image=image,
        )
    except AppError:
        # The provider failed. The safety layer still holds, so the patient gets
        # the escalation rather than an error page.
        answer = assistant.fallback_answer(assessment)
    latency_ms = int((time.perf_counter() - started) * 1000)

    # The model may have appended a booking line. It is stripped from the reply
    # whether or not it resolves — a patient must never be shown the machine
    # syntax — and only becomes an offer if a real doctor and a real free slot
    # are behind it.
    answer.answer, intent = assistant.extract_booking(answer.answer)
    proposal, problem = await _resolve_booking(db, *intent) if intent else (None, None)

    # The record says an image was attached, and nothing of what it showed:
    # the bytes are gone once this request returns.
    recorded = message if image is None else f"{message}\n[Attached image: {attachment_name}]"

    await _record_interaction(
        db,
        patient_id=patient.id,
        session_id=session_id,
        request_text=recorded,
        input_type=input_type,
        answer=answer,
        latency_ms=latency_ms,
    )

    await record_audit(
        db,
        AuditEntry(
            action=AuditAction.AI_INTERACTION,
            user_id=auth.user_id,
            actor_role=auth.role,
            patient_id=patient.id,
            entity_type="AIInteraction",
            ip_address=client_ip(request),
            request_id=getattr(request.state, "request_id", None),
            # What happened, never what was said: the question is clinical
            # content and lives in ai_interactions, not the audit log.
            metadata={
                "urgency": str(answer.urgency),
                "emergency": answer.emergency,
                "inputType": str(input_type),
                "imageAttached": image is not None,
                "interventions": answer.interventions,
                "latencyMs": latency_ms,
            },
        ),
    )

    payload = _serialize(answer, session_id)
    if proposal is not None:
        payload["booking"] = proposal
    elif problem is not None:
        # Sent as a reason rather than a sentence, so the client says it in the
        # language the reader chose — the same two languages the rest of the
        # interface already speaks — instead of the server guessing.
        payload["bookingProblem"] = problem
    return ok(payload)


async def _record_interaction(
    db: DbSession,
    *,
    patient_id: str,
    session_id: str,
    request_text: str,
    input_type: InputType,
    answer: assistant.AssistantAnswer,
    latency_ms: int,
) -> AIInteraction:
    interaction = AIInteraction(
        id=new_id(),
        patient_id=patient_id,
        session_id=session_id,
        input=request_text,
        input_type=input_type,
        extracted_symptoms=answer.extracted_symptoms,
        response=answer.answer,
        emergency_flagged=answer.emergency,
        recommended_department=answer.suggested_department,
        urgency_level=str(answer.urgency),
        model_name=answer.model_name,
        latency_ms=latency_ms,
    )
    db.add(interaction)
    await db.flush()
    return interaction


def _serialize(answer: assistant.AssistantAnswer, session_id: str) -> dict[str, Any]:
    return {
        "sessionId": session_id,
        "answer": answer.answer,
        "urgency": str(answer.urgency),
        "emergency": answer.emergency,
        "suggestedDepartment": answer.suggested_department,
        "extractedSymptoms": answer.extracted_symptoms,
        # Always sent, never optional: the client must not be able to render an
        # answer without it (§19).
        "disclaimer": answer.disclaimer,
        "safetyInterventions": answer.interventions,
    }


#: Every call spends real money at the provider, and this is the only
#: patient-reachable endpoint that does. Twenty a minute is far more than a
#: conversation needs and far less than a held-down button costs.
ChatRateLimit = Annotated[None, Depends(limit(times=20, seconds=60, scope="assistant"))]


@router.post("/chat")
async def chat(
    payload: ChatRequest,
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
    __: ChatRateLimit,
) -> dict[str, Any]:
    """Answer a patient's health question."""
    return await _answer(
        request=request,
        auth=auth,
        db=db,
        message=payload.message,
        session_id=payload.session_id,
        input_type=payload.input_type,
    )


@router.post("/chat/image")
async def chat_with_image(
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
    __: ChatRateLimit,
    image: Annotated[UploadFile, File()],
    message: Annotated[str, Form(min_length=1, max_length=MAX_QUESTION_LENGTH)],
    session_id: Annotated[str | None, Form(alias="sessionId", max_length=64)] = None,
    input_type: Annotated[InputType, Form(alias="inputType")] = InputType.TEXT,
) -> dict[str, Any]:
    """Answer a question about a photographed report or prescription.

    Multipart rather than JSON because the browser has to send bytes. The file
    goes through the same inspection as a document upload — size, sniffed
    type, declared-type agreement — and then only to the model, for this one
    answer. It is not written to storage, to the database, or to the log.
    """
    content = await image.read()
    try:
        inspected = inspect_upload(
            content,
            declared_mime=image.content_type,
            original_name=image.filename,
            max_bytes=MAX_ATTACHMENT_BYTES,
        )
    except FileRejectedError as exc:
        raise bad_request(str(exc)) from exc
    if inspected.detected_mime not in ATTACHMENT_MIME_TYPES:
        raise bad_request(
            "Attach a photo of the report as a JPEG, PNG or WebP image. "
            "PDFs and scans belong on your documents page."
        )

    return await _answer(
        request=request,
        auth=auth,
        db=db,
        message=message.strip(),
        session_id=session_id,
        input_type=input_type,
        image=(content, inspected.detected_mime),
        attachment_name=inspected.safe_name,
    )


@router.post("/symptoms")
async def analyse_symptoms(
    payload: SymptomRequest,
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
    __: ChatRateLimit,
) -> dict[str, Any]:
    """Extract symptoms from what the patient said, for them to correct.

    Writes nothing. The spec is explicit that the patient corrects the extracted
    list before anything is stored (§20), so this endpoint returns a proposal
    and the confirm endpoint is what persists.
    """
    patient = await _require_consenting_patient(auth, db)

    assessment = triage.assess(payload.text)
    context, medication_names = await _gather_context(db, patient.id)

    try:
        answer = await assistant.ask(
            f"The patient describes: {payload.text}\n\n"
            "List the symptoms they mentioned, in their own words.",
            context=context,
            triage=assessment,
            allowed_medications=medication_names,
        )
    except AppError:
        answer = assistant.fallback_answer(assessment)

    return ok(
        {
            **_serialize(answer, uuid.uuid4().hex),
            # Named so the client cannot mistake this for something saved.
            "saved": False,
            "reviewPrompt": "Are these the symptoms you meant? Edit anything that is wrong.",
        }
    )


@router.post("/symptoms/confirm", status_code=201)
async def confirm_symptoms(
    payload: ConfirmSymptomsRequest,
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
) -> dict[str, Any]:
    """Store the patient's corrected symptoms as patient-reported information.

    Deliberately *not* a medical record (spec §21, conflict C7). These rows
    carry their provenance — ``PATIENT_REPORTED`` when typed, ``AI_ASSISTED``
    when they came from speech the model transcribed — and sit in a staging
    table until a doctor promotes them. Nothing here has a clinical author.
    """
    if auth.role != Role.PATIENT or not auth.patient_id:
        raise forbidden("This endpoint is for patients.")

    # Consent is not required to record what a patient says about themselves —
    # that is their own account of their own health, and no provider is
    # involved. It is required to have the model help write it, which happened
    # in the previous step.
    source = (
        DataSource.AI_ASSISTED
        if payload.input_type == InputType.VOICE
        else DataSource.PATIENT_REPORTED
    )

    created = []
    for item in payload.symptoms:
        row = ReportedSymptom(
            id=new_id(),
            patient_id=auth.patient_id,
            symptom=item.symptom,
            severity=item.severity,
            duration_text=item.duration,
            raw_text=payload.raw_text,
            source=source,
            input_type=payload.input_type,
        )
        db.add(row)
        created.append(row)
    await db.flush()

    await record_audit(
        db,
        AuditEntry(
            action=AuditAction.AI_INTERACTION,
            user_id=auth.user_id,
            actor_role=auth.role,
            patient_id=auth.patient_id,
            entity_type="ReportedSymptom",
            ip_address=client_ip(request),
            request_id=getattr(request.state, "request_id", None),
            metadata={
                "operation": "confirm_symptoms",
                "count": len(created),
                "source": str(source),
                "inputType": str(payload.input_type),
            },
        ),
    )

    return ok(
        {
            "saved": len(created),
            "source": str(source),
            # Stated in the payload so a client cannot present these as a
            # clinician's findings.
            "note": (
                "Saved as your own account of your symptoms. This is not a "
                "diagnosis and has not been reviewed by a doctor yet."
            ),
        }
    )


@router.get("/history")
async def history(
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
    session_id: Annotated[str | None, Query(alias="sessionId", max_length=64)] = None,
    limit: Annotated[int, Query(ge=1, le=100)] = 30,
) -> dict[str, Any]:
    """The patient's own conversation history.

    Scoped to their session's patient id, so there is no id to tamper with.
    """
    if auth.role != Role.PATIENT or not auth.patient_id:
        raise forbidden("This endpoint is for patients.")

    filters = [AIInteraction.patient_id == auth.patient_id]
    if session_id:
        filters.append(AIInteraction.session_id == session_id)

    rows = (
        (
            await db.execute(
                select(AIInteraction)
                .where(*filters)
                .order_by(AIInteraction.created_at.desc())
                .limit(limit)
            )
        )
        .scalars()
        .all()
    )

    return ok(
        [
            {
                "id": row.id,
                "sessionId": row.session_id,
                "input": row.input,
                "inputType": str(row.input_type),
                "response": row.response,
                "urgency": row.urgency_level,
                "emergency": row.emergency_flagged,
                "suggestedDepartment": row.recommended_department,
                "extractedSymptoms": row.extracted_symptoms,
                "createdAt": row.created_at.isoformat() + "Z",
            }
            for row in rows
        ]
    )


@router.get("/status")
async def status(auth: CurrentAuth, db: DbSession) -> dict[str, Any]:
    """Whether the assistant is usable, and if not, why.

    Lets the client show "turn on AI consent to use this" rather than a dead
    button or an error after the fact.
    """
    available, reason = ai.availability()
    consent = False
    if auth.role == Role.PATIENT and auth.patient_id:
        patient = (
            await db.execute(select(Patient).where(Patient.id == auth.patient_id))
        ).scalar_one_or_none()
        consent = bool(patient and patient.ai_consent_active)

    return ok(
        {
            "available": available and consent,
            "providerConfigured": available,
            "consentGranted": consent,
            "reason": (
                None
                if (available and consent)
                else ("You have not granted AI consent." if available else reason)
            ),
            "disclaimer": assistant.DISCLAIMER,
        }
    )
