"""The patient health assistant (spec §18-21).

Three endpoints, and the boundaries between them are the safety design:

* ``POST /assistant/chat`` answers a question. Grounded in the patient's own
  prescriptions and appointments, validated on the way out, and escalated by a
  deterministic layer the model cannot argue with.
* ``POST /assistant/symptoms`` extracts symptoms from what the patient said —
  typed or transcribed from speech — and hands them back **for correction**. It
  writes nothing.
* ``POST /assistant/symptoms/confirm`` stores the corrected list as
  ``ReportedSymptom`` rows with source ``PATIENT_REPORTED`` or ``AI_ASSISTED``.

That last distinction is spec §21 and conflict C7: a symptom the patient
described is *patient-reported information*, not a physician's finding. It sits
in a staging table with its provenance recorded, and only a doctor's explicit
promotion turns it into a medical record. There is no code path from this module
into ``medical_records``.

Consent gates everything here: the assistant sends the patient's words to an
external provider, which is exactly what AI consent covers (conflict C2).
"""

from __future__ import annotations

import time
import uuid
from typing import Annotated, Any

from fastapi import APIRouter, Depends, Query, Request
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import select

from app.api.deps import CurrentAuth, DbSession, client_ip, require_permission
from app.api.responses import ok
from app.core.errors import AppError, ErrorCode, forbidden
from app.core.ratelimit import limit
from app.db.base import new_id, utcnow
from app.db.enums import (
    AppointmentStatus,
    AuditAction,
    DataSource,
    InputType,
    Role,
)
from app.db.models import (
    AIInteraction,
    Appointment,
    Department,
    Doctor,
    Patient,
    Prescription,
    ReportedSymptom,
    User,
)
from app.modules.appointments.schedule import to_clinic
from app.modules.audit.service import AuditEntry, record_audit
from app.modules.auth.rbac import Permission
from app.services import ai, assistant, triage

router = APIRouter(prefix="/assistant", tags=["assistant"])

RequireAiChat = Annotated[object, Depends(require_permission(Permission.AI_CHAT))]

#: A question longer than this is not a question. The cap also bounds what a
#: single request can send to the provider.
MAX_QUESTION_LENGTH = 2000


class ChatRequest(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, populate_by_name=True)

    message: Annotated[str, Field(min_length=1, max_length=MAX_QUESTION_LENGTH)]
    #: Groups turns into one conversation. Generated by the client; it only ever
    #: scopes the patient's own history, so a guessed value reveals nothing.
    session_id: str | None = Field(default=None, alias="sessionId", max_length=64)
    input_type: InputType = Field(default=InputType.TEXT, alias="inputType")


class SymptomRequest(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True, populate_by_name=True)

    text: Annotated[str, Field(min_length=1, max_length=MAX_QUESTION_LENGTH)]
    #: Accepted and validated, but not stored: this endpoint writes nothing.
    #: Provenance is recorded at the confirm step, where a row is actually
    #: created. Rejecting an unknown value here still matters — a client sending
    #: a bad one should learn about it before the patient has corrected a list.
    input_type: InputType = Field(default=InputType.TEXT, alias="inputType")


class ConfirmedSymptom(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    symptom: Annotated[str, Field(min_length=1, max_length=200)]
    severity: Annotated[str, Field(max_length=50)] | None = None
    duration: Annotated[str, Field(max_length=100)] | None = None


class ConfirmSymptomsRequest(BaseModel):
    """The patient's corrected list (spec §20: "allow the patient to correct")."""

    model_config = ConfigDict(populate_by_name=True)

    symptoms: Annotated[list[ConfirmedSymptom], Field(min_length=1, max_length=25)]
    input_type: InputType = Field(default=InputType.TEXT, alias="inputType")
    raw_text: Annotated[str, Field(max_length=MAX_QUESTION_LENGTH)] | None = Field(
        default=None, alias="rawText"
    )


async def _require_consenting_patient(auth: CurrentAuth, db: DbSession) -> Patient:
    """The assistant is for patients, and only with AI consent.

    Withdrawing consent disables this feature rather than degrading it: unlike
    document reading, there is no local model to fall back to, and the honest
    answer is to say the feature is off.
    """
    if auth.role != Role.PATIENT or not auth.patient_id:
        raise forbidden("The health assistant is for patients.")

    patient = (
        await db.execute(select(Patient).where(Patient.id == auth.patient_id))
    ).scalar_one_or_none()
    if patient is None:
        raise forbidden("This account has no patient record.")

    if not patient.ai_consent_active:
        raise AppError(
            403,
            ErrorCode.CONSENT_REQUIRED,
            "The health assistant needs your consent to process what you write. "
            "You can turn it on in your profile, and turn it off again at any time.",
        )
    return patient


async def _gather_context(db: DbSession, patient_id: str) -> tuple[str, list[str]]:
    """The patient's own data, and the medications the answer may mention.

    Returned together because they are the same fact used twice: as grounding
    for the model, and afterwards as the list any named drug is checked against.
    """
    medications = (
        (
            await db.execute(
                select(Prescription.medication, Prescription.dosage, Prescription.frequency)
                .where(Prescription.patient_id == patient_id, Prescription.active.is_(True))
                .limit(25)
            )
        )
        .all()
    )
    medication_names = [row.medication for row in medications]
    medication_lines = [
        f"{row.medication} {row.dosage} {row.frequency}" for row in medications
    ]

    appointments = (
        await db.execute(
            select(Appointment.start_time, User.name, Doctor.specialization)
            .join(Doctor, Doctor.id == Appointment.doctor_id)
            .join(User, User.id == Doctor.user_id)
            .where(
                Appointment.patient_id == patient_id,
                Appointment.start_time >= utcnow(),
                Appointment.status.in_(
                    [AppointmentStatus.REQUESTED, AppointmentStatus.CONFIRMED]
                ),
            )
            .order_by(Appointment.start_time)
            .limit(5)
        )
    ).all()
    appointment_lines = [
        f"{to_clinic(row.start_time).strftime('%d %b %Y at %H:%M')} with {row.name}"
        f" ({row.specialization})"
        for row in appointments
    ]

    departments = (
        (await db.execute(select(Department.name).where(Department.active.is_(True)).limit(30)))
        .scalars()
        .all()
    )

    context = assistant.build_context(
        active_medications=medication_lines,
        upcoming_appointments=appointment_lines,
        departments=list(departments),
    )
    return context, medication_names


async def _record_interaction(
    db: DbSession,
    *,
    patient_id: str,
    session_id: str,
    request_text: str,
    input_type: InputType,
    answer: assistant.AssistantAnswer,
    latency_ms: int,
) -> AIInteraction:
    interaction = AIInteraction(
        id=new_id(),
        patient_id=patient_id,
        session_id=session_id,
        input=request_text,
        input_type=input_type,
        extracted_symptoms=answer.extracted_symptoms,
        response=answer.answer,
        emergency_flagged=answer.emergency,
        recommended_department=answer.suggested_department,
        urgency_level=str(answer.urgency),
        model_name=answer.model_name,
        latency_ms=latency_ms,
    )
    db.add(interaction)
    await db.flush()
    return interaction


def _serialize(answer: assistant.AssistantAnswer, session_id: str) -> dict[str, Any]:
    return {
        "sessionId": session_id,
        "answer": answer.answer,
        "urgency": str(answer.urgency),
        "emergency": answer.emergency,
        "suggestedDepartment": answer.suggested_department,
        "extractedSymptoms": answer.extracted_symptoms,
        # Always sent, never optional: the client must not be able to render an
        # answer without it (§19).
        "disclaimer": answer.disclaimer,
        "safetyInterventions": answer.interventions,
    }


#: Every call spends real money at the provider, and this is the only
#: patient-reachable endpoint that does. Twenty a minute is far more than a
#: conversation needs and far less than a held-down button costs.
ChatRateLimit = Annotated[None, Depends(limit(times=20, seconds=60, scope="assistant"))]


@router.post("/chat")
async def chat(
    payload: ChatRequest,
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
    __: ChatRateLimit,
) -> dict[str, Any]:
    """Answer a patient's health question.

    Note the order: triage runs before the provider is contacted, so an
    emergency is escalated even when the provider is down, slow, or wrong.
    """
    patient = await _require_consenting_patient(auth, db)
    session_id = payload.session_id or uuid.uuid4().hex

    assessment = triage.assess(payload.message)
    context, medication_names = await _gather_context(db, patient.id)

    started = time.perf_counter()
    try:
        answer = await assistant.ask(
            payload.message,
            context=context,
            triage=assessment,
            allowed_medications=medication_names,
        )
    except AppError:
        # The provider failed. The safety layer still holds, so the patient gets
        # the escalation rather than an error page.
        answer = assistant.fallback_answer(assessment)
    latency_ms = int((time.perf_counter() - started) * 1000)

    await _record_interaction(
        db,
        patient_id=patient.id,
        session_id=session_id,
        request_text=payload.message,
        input_type=payload.input_type,
        answer=answer,
        latency_ms=latency_ms,
    )

    await record_audit(
        db,
        AuditEntry(
            action=AuditAction.AI_INTERACTION,
            user_id=auth.user_id,
            actor_role=auth.role,
            patient_id=patient.id,
            entity_type="AIInteraction",
            ip_address=client_ip(request),
            request_id=getattr(request.state, "request_id", None),
            # What happened, never what was said: the question is clinical
            # content and lives in ai_interactions, not the audit log.
            metadata={
                "urgency": str(answer.urgency),
                "emergency": answer.emergency,
                "inputType": str(payload.input_type),
                "interventions": answer.interventions,
                "latencyMs": latency_ms,
            },
        ),
    )

    return ok(_serialize(answer, session_id))


@router.post("/symptoms")
async def analyse_symptoms(
    payload: SymptomRequest,
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
    __: ChatRateLimit,
) -> dict[str, Any]:
    """Extract symptoms from what the patient said, for them to correct.

    Writes nothing. The spec is explicit that the patient corrects the extracted
    list before anything is stored (§20), so this endpoint returns a proposal
    and the confirm endpoint is what persists.
    """
    patient = await _require_consenting_patient(auth, db)

    assessment = triage.assess(payload.text)
    context, medication_names = await _gather_context(db, patient.id)

    try:
        answer = await assistant.ask(
            f"The patient describes: {payload.text}\n\n"
            "List the symptoms they mentioned, in their own words.",
            context=context,
            triage=assessment,
            allowed_medications=medication_names,
        )
    except AppError:
        answer = assistant.fallback_answer(assessment)

    return ok(
        {
            **_serialize(answer, uuid.uuid4().hex),
            # Named so the client cannot mistake this for something saved.
            "saved": False,
            "reviewPrompt": "Are these the symptoms you meant? Edit anything that is wrong.",
        }
    )


@router.post("/symptoms/confirm", status_code=201)
async def confirm_symptoms(
    payload: ConfirmSymptomsRequest,
    request: Request,
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
) -> dict[str, Any]:
    """Store the patient's corrected symptoms as patient-reported information.

    Deliberately *not* a medical record (spec §21, conflict C7). These rows
    carry their provenance — ``PATIENT_REPORTED`` when typed, ``AI_ASSISTED``
    when they came from speech the model transcribed — and sit in a staging
    table until a doctor promotes them. Nothing here has a clinical author.
    """
    if auth.role != Role.PATIENT or not auth.patient_id:
        raise forbidden("This endpoint is for patients.")

    # Consent is not required to record what a patient says about themselves —
    # that is their own account of their own health, and no provider is
    # involved. It is required to have the model help write it, which happened
    # in the previous step.
    source = (
        DataSource.AI_ASSISTED
        if payload.input_type == InputType.VOICE
        else DataSource.PATIENT_REPORTED
    )

    created = []
    for item in payload.symptoms:
        row = ReportedSymptom(
            id=new_id(),
            patient_id=auth.patient_id,
            symptom=item.symptom,
            severity=item.severity,
            duration_text=item.duration,
            raw_text=payload.raw_text,
            source=source,
            input_type=payload.input_type,
        )
        db.add(row)
        created.append(row)
    await db.flush()

    await record_audit(
        db,
        AuditEntry(
            action=AuditAction.AI_INTERACTION,
            user_id=auth.user_id,
            actor_role=auth.role,
            patient_id=auth.patient_id,
            entity_type="ReportedSymptom",
            ip_address=client_ip(request),
            request_id=getattr(request.state, "request_id", None),
            metadata={
                "operation": "confirm_symptoms",
                "count": len(created),
                "source": str(source),
                "inputType": str(payload.input_type),
            },
        ),
    )

    return ok(
        {
            "saved": len(created),
            "source": str(source),
            # Stated in the payload so a client cannot present these as a
            # clinician's findings.
            "note": (
                "Saved as your own account of your symptoms. This is not a "
                "diagnosis and has not been reviewed by a doctor yet."
            ),
        }
    )


@router.get("/history")
async def history(
    auth: CurrentAuth,
    db: DbSession,
    _: RequireAiChat,
    session_id: Annotated[str | None, Query(alias="sessionId", max_length=64)] = None,
    limit: Annotated[int, Query(ge=1, le=100)] = 30,
) -> dict[str, Any]:
    """The patient's own conversation history.

    Scoped to their session's patient id, so there is no id to tamper with.
    """
    if auth.role != Role.PATIENT or not auth.patient_id:
        raise forbidden("This endpoint is for patients.")

    filters = [AIInteraction.patient_id == auth.patient_id]
    if session_id:
        filters.append(AIInteraction.session_id == session_id)

    rows = (
        (
            await db.execute(
                select(AIInteraction)
                .where(*filters)
                .order_by(AIInteraction.created_at.desc())
                .limit(limit)
            )
        )
        .scalars()
        .all()
    )

    return ok(
        [
            {
                "id": row.id,
                "sessionId": row.session_id,
                "input": row.input,
                "inputType": str(row.input_type),
                "response": row.response,
                "urgency": row.urgency_level,
                "emergency": row.emergency_flagged,
                "suggestedDepartment": row.recommended_department,
                "extractedSymptoms": row.extracted_symptoms,
                "createdAt": row.created_at.isoformat() + "Z",
            }
            for row in rows
        ]
    )


@router.get("/status")
async def status(auth: CurrentAuth, db: DbSession) -> dict[str, Any]:
    """Whether the assistant is usable, and if not, why.

    Lets the client show "turn on AI consent to use this" rather than a dead
    button or an error after the fact.
    """
    available, reason = ai.availability()
    consent = False
    if auth.role == Role.PATIENT and auth.patient_id:
        patient = (
            await db.execute(select(Patient).where(Patient.id == auth.patient_id))
        ).scalar_one_or_none()
        consent = bool(patient and patient.ai_consent_active)

    return ok(
        {
            "available": available and consent,
            "providerConfigured": available,
            "consentGranted": consent,
            "reason": (
                None
                if (available and consent)
                else ("You have not granted AI consent." if available else reason)
            ),
            "disclaimer": assistant.DISCLAIMER,
        }
    )
