"""Web Push delivery.

A push is the only channel that reaches somebody who is not looking at the
site, which is what a reminder to take a tablet has to do. It is also the only
one that goes through a third party we do not control — Google's, Apple's or
Mozilla's push service, depending on the browser — so what it carries matters.

**The payload is encrypted to the device, not to the push service.** The keys
in a subscription (``p256dh`` and ``auth``) are generated by the browser, and
the message is sealed to them before it leaves. The service in the middle
routes ciphertext it cannot open. That is what makes it acceptable to name a
medicine in one.

**It still says as little as it can.** Even sealed, a push is displayed on a
lock screen, which is a surface a patient does not control. Titles and bodies
come from the same templates the in-app notifications use, which are written to
be readable over somebody's shoulder.

**A dead endpoint is retired, not retried.** A push service answering 404 or
410 is telling us the subscription is gone — the browser was reinstalled, the
permission revoked. Retrying that forever would be a queue that never drains,
so the row is stamped and skipped from then on.
"""

from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass
from typing import Any

from app.core.config import settings
from app.core.logging import logger


@dataclass(frozen=True)
class Subscription:
    """The four fields a browser hands over, and the row they came from."""

    id: str
    endpoint: str
    p256dh: str
    auth: str


@dataclass(frozen=True)
class Delivery:
    """What happened, in the only two shapes the caller acts on."""

    ok: bool
    #: True when the push service says this subscription no longer exists, so
    #: the caller retires the row instead of leaving it to be retried.
    gone: bool = False
    error: str | None = None


def _info(subscription: Subscription) -> dict[str, Any]:
    return {
        "endpoint": subscription.endpoint,
        "keys": {"p256dh": subscription.p256dh, "auth": subscription.auth},
    }


def _send_blocking(subscription: Subscription, payload: str) -> Delivery:
    """The actual HTTPS call. Runs off the event loop; see `send`."""
    try:
        from pywebpush import WebPushException, webpush
    except ImportError:  # pragma: no cover - only when the extra is absent
        return Delivery(ok=False, error="pywebpush is not installed")

    try:
        webpush(
            subscription_info=_info(subscription),
            data=payload,
            vapid_private_key=settings.VAPID_PRIVATE_KEY,
            vapid_claims={"sub": settings.VAPID_SUBJECT},
            timeout=10,
        )
        return Delivery(ok=True)
    except WebPushException as exc:
        status = getattr(exc.response, "status_code", None)
        # 404/410 mean the subscription is gone for good. Everything else —
        # a rate limit, a 5xx, a timeout — may work next time.
        return Delivery(ok=False, gone=status in (404, 410), error=f"{status}: {exc}")
    except Exception as exc:
        # A push must never be able to take the dispatcher down with it.
        return Delivery(ok=False, error=type(exc).__name__)


async def send(subscription: Subscription, *, title: str, body: str, link: str | None, tag: str) -> Delivery:
    """Deliver one message to one device.

    `pywebpush` is synchronous and does network I/O, so it is run in a thread:
    calling it directly would block the event loop for the length of a request
    to a push service, and the dispatcher sends these in batches.

    `tag` is what lets a phone replace a notification rather than stack it —
    three reminders for the same prescription should be one line on a lock
    screen, not three.
    """
    if not settings.push_enabled:
        return Delivery(ok=False, error="push is not configured")

    payload = json.dumps(
        {"title": title, "body": body, "link": link, "tag": tag},
        ensure_ascii=False,
    )
    result = await asyncio.to_thread(_send_blocking, subscription, payload)
    if not result.ok and not result.gone:
        logger.info("push_failed", endpoint=subscription.endpoint[-24:], error=result.error)
    return result
